### ISSUE TITLE
nodegit doesn't build nor install on node version 10

### ISSUE THREAD

**Issue by trieloff** [adobe/git-server#13]
Homebrew's latest node formula is for Node 10.8, but according to nodegit/nodegit#1532 only Node 10.3 works.

**Comment by stefan-guggisberg** [comment]
current nodegit (v0.22.2) doesn't build nor install on node v10.*.*.

see https://github.com/nodegit/nodegit/issues/1490

workaround for the time being: use node v8

**Comment by trieloff** [comment]
I downgraded to node 8, but this might be a reason to consider using https://github.com/es-git/es-git as a fallback.

**Comment by stefan-guggisberg** [comment]
as a workaround, you can use the binary distribution of `hlx` which is agnostic to the current node environment (see https://github.com/adobe/helix-cli/issues/127).

[hlx_install.sh](https://github.com/adobe/helix-cli/releases/download/v0.3.2/hlx_install.sh)

**Comment by stefan-guggisberg** [comment]
fixed by using [@adobe/nodegit](https://www.npmjs.com/package/@adobe/nodegit) built on [adobe/nodegit](https://github.com/adobe/nodegit), a `nodegit` fork with PR https://github.com/nodegit/nodegit/pull/1519 applied.

**Comment by stefan-guggisberg** [comment]
once `node 10` is supported in the official `nodegit` project i'll revert to using the official `nodegit` npm package.

**Comment by stefan-guggisberg** [comment]
reopening, since long build times made us revert to using official `nodegit/nodegit` v0.22.2

**Comment by stefan-guggisberg** [comment]
the latest [nodegit release](https://github.com/nodegit/nodegit/releases/tag/v0.23.0) is a major improvement, e.g.:

* node 10 support
* doesn't compile openssl

however, there's now an issue with node 8: https://github.com/nodegit/nodegit/issues/1575

we'll have to wait until said issue gets fixed before we can update the `nodegit`dependency to `0.23.?`.

**Comment by stefan-guggisberg** [comment]
an update to `nodegit v0.23.0` and https://github.com/nodegit/nodegit/issues/1575:

apparently node v8.12 and v10 work. i was using node v8.9 and ran into above issue.

**Comment by stefan-guggisberg** [comment]
fixed in 723c954
