### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by trieloff** [adobe/git-server#17]
I think we should cut a proper release (maybe 0.1.0), so that petridish does not have to depend on snapshots anymore.

**Comment by tripodsan** [comment]
we already have released 0.2.0: https://www.npmjs.com/package/@adobe/git-server

**Comment by tripodsan** [comment]
also see: https://github.com/adobe/git-server/releases/tag/v0.0.2

**Comment by trieloff** [comment]
Ok, then changing the package.json version to 0.3.0 will make sure we get 0.3.0-* snapshots.

**Comment by tripodsan** [comment]
good practice to fill in the release-notes of releases.

**Comment by trieloff** [comment]
Oh, and we would jump to 0.0.3 - not 0.3.0

**Comment by tripodsan** [comment]
I'm not happy with the release concepts. I'm never sure if the snapshots are higher than the released version. maybe we should use the odd/even release scheme.

**Comment by tripodsan** [comment]
so current release process is:
```
$ npm version patch
$ git push && git push --tags
$ npm publish
$ npm version patch
$ git push
```
