### ISSUE TITLE
v3-api Get archive link with annotated tags didn't work

### ISSUE THREAD

**Issue by dbrandes-welfenlab** [adobe/git-server#230]
Hi,

thanks for publishing this great software! I started to work with it, but gets into the following bug:

**Description**
archive download from repos at an annotated tag results in an error. This is because the tag does not contain tree, but object (line lib/archiveHandler.js:180).

**To Reproduce**
1. start server and get repo from https://github.com/dbrandes-welfenlab/rules_cc.git
2. try wget http://localhost:5000/dbrandes-welfenlab/rules_cc/archive/v2020.10.01.zip works well (lightweight tag)
3. try wget http://localhost:5000/dbrandes-welfenlab/rules_cc/archive/v2020.10.01a.zip did not work (Annotated tag)

Error:

```
MissingParameterError: The function requires a "oid" parameter but none was provided.
    at assertParameter (/source/git_server/node_modules/isomorphic-git/index.cjs:4227:11)
     at Object.readObject (/source/git_server/node_modules/isomorphic-git/index.cjs:10944:5)
     at getObject (/source/git_server/lib/git.js:218:14)
     at /source/git_server/lib/archiveHandler.js:180:37
```

and on the wget side:

```
--2020-10-04 18:16:24--  http://172.21.75.103:5000/dbrandes-welfenlab/rules_cc/archive/v2020.10.01.zip
Verbindungsaufbau zu 172.21.75.103:5000 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 302 Found
Platz: http://172.21.75.103:5000/codeload/dbrandes-welfenlab/rules_cc/zip/v2020.10.01 [folgend]
--2020-10-04 18:16:25--  http://172.21.75.103:5000/codeload/dbrandes-welfenlab/rules_cc/zip/v2020.10.01
Wiederverwendung der bestehenden Verbindung zu 172.21.75.103:5000.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 500 Internal Server Error
2020-10-04 18:16:25 FEHLER 500: Internal Server Error.
```

**Expected behavior**
gets a file with wget.

**Environment**
Specify your Node version and Operating System:
node:12 docker container.

best regards,

Daniel Brandes

**Comment by stefan-guggisberg** [comment]
Thanks for reporting this issue!

**Comment by dbrandes-welfenlab** [comment]
Thanks for the fast fix!
