### ISSUE TITLE
Add support for a local-files only raw mode.

### ISSUE THREAD

**Issue by tripodsan** [adobe/git-server#234]
**Is your feature request related to a problem? Please describe.**
In many cases, serving the raw files from the git repository can lead to confusing results, for example when a file is missing in the local checkout, but present in the repository.

in those situations, it would be more transparent to only serve the files directly from disk and never from the repository.

one question is if the current branch should be respected or not. e.g. if the requested branch doesn't match the local checkout branch, it could either respond with a 404 or 400 or just ignore.

/cc @davidnuescheler

**Comment by stefan-guggisberg** [comment]
won't fix
