### ISSUE TITLE
Revert to official nodegit 0.2.22

### ISSUE THREAD

**Issue by tripodsan** [adobe/git-server#32]
while the forked nodegit addresses some security issues, it slows down development significantly, since we don't provide the pre-built binaries. some developers have even problems building nodegit at all.

Suggest 
- revert back to nodegit 0.2.22

**Comment by stefan-guggisberg** [comment]
the forked nodegit addresses all currentlyknown vulnerabilities and provides node 10 support. 

but i agree the looong build time is a pain. i'll revert to v0.22.2 for now.

> some developers

;-)

**Comment by stefan-guggisberg** [comment]
fixed in cf264e8399dff331f1ede06f8e6ee31e23334539 (v0.9.6)
