### ISSUE TITLE
Explore pure JS alternatives to native nodegit

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/git-server#41]
`nodegit` is a heavy, native dependency. the build process is brittle and likely to break with the next major node version. 

using a pure js alternative would likely reduce the size of the installed `git-server` and improve the speed, stability and cross platform compatibility of `git-server` installation process.

some candidates:

* https://github.com/SamyPesse/gitkit-js
* https://github.com/isomorphic-git/isomorphic-git
* https://github.com/es-git/es-git

**Comment by mojavelinux** [comment]
I have had a very bad experience using nodegit as a dependency for my application. I strongly recommend isomorphic-git. The maintainer is very knowledge and responsive. As a result, the project is making huge advances very quickly.

**Comment by stefan-guggisberg** [comment]
@mojavelinux thanks for feedback, appreciated!

**Comment by mojavelinux** [comment]
You might also be interested to know that @wmhilton is working on the server part as well. Once that's done, you won't need to delegate to the git command using spawn. I'm sure he can tell you more about it.

**Comment by stefan-guggisberg** [comment]
> some candidates:
> 
> https://github.com/SamyPesse/gitkit-js
> https://github.com/isomorphic-git/isomorphic-git
> https://github.com/es-git/es-git

from above alternatives [isomorphic-git](https://github.com/isomorphic-git/isomorphic-git) seems by far the most mature and most active project (based on # of issues, PRs, stars). 

[es-git](https://github.com/es-git/es-git) (forked from tim caswell's [js-git](https://github.com/creationix/js-git)) seems to be a one man show, and based on above criteria, not very active. 

[gitkit-js](https://github.com/SamyPesse/gitkit-js) is abandoned (last commit 3 years ago).

we'll go with `isomorphic-git` then.

**Comment by stefan-guggisberg** [comment]
@mojavelinux, cc @wmhilton 
It's been quiet lately at isomorphic-git. We've created some issues and PR but haven't heard back in a month. Should I be concerned?

**Comment by wmhilton** [comment]
Nope! I just got distracted by moving to Florida. The development pace of isomorphic-git is about to pick up again!
