### ISSUE TITLE
Logging is hard to tune

### ISSUE THREAD

**Issue by mojavelinux** [adobe/git-server#46]
I've been evaluating using this library in a test suite for an application that performs git operations. In that context, I don't want and logging output from the git server because it clutters the output of the test framework. Thus, I'd like to be able to silence the logger (or at least disable anything less than error messages). However, I've been unable to figure out how to do that short of modifying the global logger object.

This could be a docs issue, or it could go deeper. At the very least, I'd be interested in being able to completely disable logging with a switch. But just knowing how to replace the logger with a custom one would be helpful.

**Comment by trieloff** [comment]
It's a real issue. In the other helix packages, we allow passing a logger (Winston), git-server uses a hardcoded logger.

**Comment by stefan-guggisberg** [comment]
> It's a real issue. In the other helix packages, we allow passing a logger (Winston), git-server uses a hardcoded logger.

that's fixed as of c34e2ed (#18)

**Comment by stefan-guggisberg** [comment]
@mojavelinux log levels were broken, fixed in 9593a06. 

setting `logs.level` to `error` in the configuration (`config.js`) will mute all but error messages.

you can also use your own winston logger instance  (#18), however that's still undocumented:

```javascript
// git server
const gitServer = require('@adobe/git-server/lib/server.js');
// git server config
const config = require('./config.js');
// inject winston logger instance
config.logger = require('winston').createLogger({ /* ... */ });

gitServer.start(config);
``` 

i'll add docu to the README.

**Comment by stefan-guggisberg** [comment]
@mojavelinux does that work for you?

**Comment by stefan-guggisberg** [comment]
closing, please feel free to open a new issue if there's still a problem.
