### ISSUE TITLE
Support codeload.github.com

### ISSUE THREAD

**Issue by trieloff** [adobe/git-server#5]
For adobe/project-helix#101 I need to get full snapshots of the Git Repository at a certain revision.

I assume that downloading the tarball from GitHub will be faster than cloning the entire repository (especially given that I will discard the download afterwards), which means we need to reverse-engineer the "Download ZIP" functionality.

For instance, clicking "Download ZIP" will open this URL `https://github.com/adobe/parcel-plugin-htl/archive/master.zip` which then 302s to `https://codeload.github.com/adobe/parcel-plugin-htl/zip/master`

`master` can in both cases be replaced with a ref identifier.

**Comment by stefan-guggisberg** [comment]
will support both (official and unofficial) endpoints that redirect:
* `https://api.github.com/repos/adobe/parcel-plugin-htl/zipball/master` (official, rate limited, redirects)
* `https://github.com/adobe/parcel-plugin-htl/archive/master.zip` (unofficial, not rate limited, redirects)
as well as the target endpoint: 
* `https://codeload.github.com/adobe/parcel-plugin-htl/zip/master` (unofficial, not rate limited, doesn't redirect)

related discussions:

https://github.com/composer/composer/pull/4737#issuecomment-167802243
https://github.com/hirak/prestissimo/issues/65#issuecomment-192899060

**Comment by stefan-guggisberg** [comment]
implemented in 3f6c72b2ba44aba05e41e6a29c7f202d36073e16
