### ISSUE TITLE
Support for refs with slashes for content requests

### ISSUE THREAD

**Issue by tripodsan** [adobe/git-server#53]
`ref` that contain a slash, eg `issues/234` are not supported everywhere in the github server.

**Comment by tripodsan** [comment]
added tests in https://github.com/adobe/git-server/pull/54/commits/a27fb54aee360c465287689f18a69ffa75598919

**Comment by stefan-guggisberg** [comment]
fixed in ddac16c7abdd8e71fd1bb929b36f4bd440657522
