### ISSUE TITLE
Server refuses to deliver content on `config` branch

### ISSUE THREAD

**Issue by tripodsan** [adobe/git-server#55]
on branch with the name `config`, the server does not deliver raw content.

**Comment by tripodsan** [comment]
created branch: https://github.com/adobe/git-server/tree/config-branch/

with added test case: https://github.com/adobe/git-server/commit/714354a4d9672d57bf2132d5d7c9a707e43e0561

**Comment by tripodsan** [comment]
I can't find anything wrong in git-server; maybe a problem of isomorphic git.

**Comment by stefan-guggisberg** [comment]
It's an `isomorphic-git` bug:
* https://github.com/isomorphic-git/isomorphic-git/issues/709
* https://github.com/isomorphic-git/isomorphic-git/pull/710

For the time being, if possible, avoid the following branch names:
`config`, `description`, `index`, `shallow`, `commondir`

**Comment by stefan-guggisberg** [comment]
fixed in 6ab99c1
