### ISSUE TITLE
Server serves files wrongly on case insensitive filesystems

### ISSUE THREAD

**Issue by tripodsan** [adobe/git-server#66]
running on a case insensitive filesystem, the git-server serves files wrongly, if their path only differs in case.

for example:

```
http://localhost:${state.httpPort}/raw/owner1/repo1/master/readme.md
```

responds with the contents of the `README.md`,

but a similar request on github doesn't:

```
https://raw.githubusercontent.com/adobe/git-server/master/readme.md
```

**Comment by stefan-guggisberg** [comment]
related: https://github.com/isomorphic-git/isomorphic-git/issues/752
